add FanTop address
blocto/flow-transactions pull request #47
Opened 2023-07-28 09:11 UTC by sone-md

Thank you always for your support. 
Following the content here, I have created a PR to add our service. I'd be happy if you could check it.

https://docs.blocto.app/blocto-sdk/javascript-sdk/flow/verified-transaction

Our Service FanTop
https://fantop.jp/
We are currently in the final stages of preparing for the transition to v2.

2023-07-28 10:12 UTC, scottphc commented
Hi @sone-md, please add your all related transactions and messages to this project. You can refer to https://github.com/blocto/flow-transactions/pull/43/files

2023-07-31 05:27 UTC, sone-md commented
@scottphc 
Thank you for your confirmation. I've added a transaction, so please check it. 
Since there are multiple testnet environments, I've decided to exclude them.

2023-07-31 08:03 UTC, scottphc commented
@sone-md you also need to add the message https://github.com/blocto/flow-transactions/pull/43/files#diff-28752302d8186f6037fcf0d341602d6d5930f4465fd029b6f7b87eb5eed635eaR1-R9. It will show the localized message to users for better user experience. 

For example, [transactions/FanTop/transfer_token.json](https://github.com/blocto/flow-transactions/pull/47/files#diff-5cda58d81b7d354f8da82a7aba8cbbbb19237a1ece36d549a9d9ed4d82704ea9) can be:
```
{
  "arguments": ["id", "to"],
  "messages": {
    "en": "Transfer FanTop NFT to {to}",
    "ja": "YOUR JAPANESE TRANSLATION"
  }
}
```

2023-07-31 10:46 UTC, sone-md commented
@scottphc 
How is this "message" displayed? If there are any documents or samples, please teach me. I set it at the time of transaction execution, but I could not confirm the display.

```
fcl.mutate({
      message: "FanTopトークンを格納するための保管庫を作成します",
      cadence,
      proposer: fcl.currentUser,
      limit: 1000,
    });
```

2023-07-31 15:36 UTC, scottphc commented
@sone-md I mean you can update this file [transactions/FanTop/transfer_token.json](https://github.com/blocto/flow-transactions/pull/47/files#diff-5cda58d81b7d354f8da82a7aba8cbbbb19237a1ece36d549a9d9ed4d82704ea9)

```
{
  "arguments": ["id", "to"],
  "messages": {
    "en": "Transfer FanTop NFT to {to}",
    "ja": "YOUR JAPANESE TRANSLATION"
  }
}
```

And once we merge and update it, the message `Transfer FanTop NFT to 0x1234567890` will show up in the Blocto wallet.

2023-08-01 07:35 UTC, sone-md commented
@scottphc I've added a message. How does it look with this kind of image?

2023-08-01 07:48 UTC, scottphc requested changes
LGTM, just minor update.

2023-08-01 07:48 UTC, scottphc commented on transactions/FanTop/initialize_collection.json
> +    "en": "I will create a storage vault to store FanTop's items.",
Starting with the verb is better, just like other json file you wrote.
```suggestion
    "en": "Create a storage vault to store FanTop's items.",
```

2023-08-01 07:55 UTC, scottphc approved these changes

2023-08-01 07:56 UTC, merged